package gs.web.school.usp;

import gs.data.school.EspResponse;
import org.joda.time.DateTime;

import java.util.*;


/**
 * Not thread safe
 */
public class BaseEspResponseData implements IEspResponseData {

    // the wrapped list of responses
    private List<EspResponse> _responses;

    private Map<String, List<EspResponse>> _responsesByKey = null;
    private Date _oldestResponseDate = null;

    protected void clearCache() {
        _responsesByKey = null;
        _oldestResponseDate = null;
    }

    public BaseEspResponseData(List<EspResponse> responses) {
        if (responses == null) {
            responses = new ArrayList<EspResponse>();
        }
        _responses = responses;
    }

    public BaseEspResponseData() {
        _responses = new ArrayList<EspResponse>();
    }

    public Date getOldestResponseDate() {
        if (_responses == null || _responses.isEmpty()) {
            return null;
        }

        if (_oldestResponseDate == null) {
            Date oldestResponse = null;
            for (EspResponse response : _responses) {
                if (oldestResponse == null || response.getCreated().before(oldestResponse)) {
                    oldestResponse = response.getCreated();
                }
            }
            _oldestResponseDate = oldestResponse;
        }
        return _oldestResponseDate;
    }

    public boolean hasRecentYearOfData() {
        if (getOldestResponseDate() == null) {
            return false;
        }

        DateTime yearAgo = new DateTime().minusYears(1);
        DateTime oldestResponseDate = new DateTime(getOldestResponseDate());

        return yearAgo.isBefore(oldestResponseDate);
    }

    public List<EspResponse> getResponses() {
        return _responses;
    }

    public Map<String, List<EspResponse>> getResponsesByKey() {
        if (_responses == null || _responses.isEmpty()) {
            return new HashMap<String, List<EspResponse>>();
        }

        if (_responsesByKey == null) {
            _responsesByKey = new HashMap<String, List<EspResponse>>();
        }

        Iterator<EspResponse> iterator = iterator();

        while (iterator.hasNext()) {
            EspResponse response = iterator.next();

            List<EspResponse> responses = _responsesByKey.get(response.getKey());

            if (responses == null) {
                responses = new ArrayList<EspResponse>();
                _responsesByKey.put(response.getKey(), responses);
            }
            responses.add(response);
        }

        return _responsesByKey;
    }

    @Override
    public String toString() {
        return _responses.toString();
    }

    // delegate methods to _responses generated by IntelliJ:

    public int size() {
        return _responses.size();
    }

    public boolean isEmpty() {
        return _responses.isEmpty();
    }

    public boolean contains(Object o) {
        return _responses.contains(o);
    }

    public Iterator<EspResponse> iterator() {
        return _responses.iterator();
    }

    public Object[] toArray() {
        return _responses.toArray();
    }

    public <T> T[] toArray(T[] ts) {
        return _responses.toArray(ts);
    }

    public final boolean add(EspResponse espResponse) {
        clearCache();
        return _responses.add(espResponse);
    }

    public final boolean remove(Object o) {
        clearCache();
        return _responses.remove(o);
    }

    public boolean containsAll(Collection<?> objects) {
        return _responses.containsAll(objects);
    }

    public final boolean addAll(Collection<? extends EspResponse> espResponses) {
        clearCache();
        return _responses.addAll(espResponses);
    }

    public final boolean addAll(int i, Collection<? extends EspResponse> espResponses) {
        clearCache();
        return _responses.addAll(i, espResponses);
    }

    public final boolean removeAll(Collection<?> objects) {
        clearCache();
        return _responses.removeAll(objects);
    }

    public final boolean retainAll(Collection<?> objects) {
        clearCache();
        return _responses.retainAll(objects);
    }

    public final void clear() {
        clearCache();
        _responses.clear();
    }

    @Override
    public boolean equals(Object o) {
        return _responses.equals(o);
    }

    @Override
    public int hashCode() {
        return _responses.hashCode();
    }

    public EspResponse get(int i) {
        return _responses.get(i);
    }

    public EspResponse set(int i, EspResponse espResponse) {
        return _responses.set(i, espResponse);
    }

    public final void add(int i, EspResponse espResponse) {
        clearCache();
        _responses.add(i, espResponse);
    }

    public final EspResponse remove(int i) {
        clearCache();
        return _responses.remove(i);
    }

    public int indexOf(Object o) {
        return _responses.indexOf(o);
    }

    public int lastIndexOf(Object o) {
        return _responses.lastIndexOf(o);
    }

    public ListIterator<EspResponse> listIterator() {
        return _responses.listIterator();
    }

    public ListIterator<EspResponse> listIterator(int i) {
        return _responses.listIterator(i);
    }

    public List<EspResponse> subList(int i, int i2) {
        return _responses.subList(i, i2);
    }
}
